"""Wi-Fi credentials for Fleet Manager firmware builds (gitignored JSON + header injection)."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "data"
WIFI_CONFIG_JSON = DATA_DIR / "wifi_config.json"

LOCAL_H_HEADER = """#pragma once
// Auto-generated by Fleet Manager — do not edit by hand.

static const char *WIFI_SSID = "{ssid}";
static const char *WIFI_PASSWORD = "{password}";
"""


def _escape_c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def load_saved() -> dict | None:
    if not WIFI_CONFIG_JSON.exists():
        return None
    try:
        data = json.loads(WIFI_CONFIG_JSON.read_text(encoding="utf-8"))
        ssid = (data.get("ssid") or "").strip()
        password = data.get("password") or ""
        if ssid:
            return {
                "ssid": ssid,
                "password": password,
                "saved_at": data.get("saved_at"),
            }
    except (OSError, json.JSONDecodeError):
        pass
    return None


def save(ssid: str, password: str) -> str:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    saved_at = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M:%S")
    WIFI_CONFIG_JSON.write_text(
        json.dumps(
            {"ssid": ssid.strip(), "password": password, "saved_at": saved_at},
            indent=2,
        ),
        encoding="utf-8",
    )
    return saved_at


def import_from_pico_robot(firmware_root: Path) -> dict | None:
    """Parse wifi_config.local.h from pico_robot if present."""
    path = firmware_root / "pico_robot" / "include" / "wifi_config.local.h"
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    ssid_m = re.search(r'WIFI_SSID\s*=\s*"([^"]*)"', text)
    pass_m = re.search(r'WIFI_PASSWORD\s*=\s*"([^"]*)"', text)
    if not ssid_m:
        return None
    return {"ssid": ssid_m.group(1), "password": pass_m.group(1) if pass_m else ""}


def resolve_credentials(
    firmware_root: Path,
    wifi_ssid: str | None = None,
    wifi_password: str | None = None,
) -> dict:
    ssid = (wifi_ssid or "").strip()
    password = wifi_password if wifi_password is not None else ""

    if ssid:
        return {"ssid": ssid, "password": password}

    saved = load_saved()
    if saved:
        return saved

    imported = import_from_pico_robot(firmware_root)
    if imported:
        return imported

    raise ValueError(
        "Wi-Fi credentials not configured. Enter SSID and password in the Fleet Manager header, "
        "or save them with the Save button before flashing."
    )


def write_local_header(firmware_dir: Path, ssid: str, password: str) -> Path:
    include_dir = firmware_dir / "include"
    include_dir.mkdir(parents=True, exist_ok=True)
    out_path = include_dir / "wifi_config.local.h"
    content = LOCAL_H_HEADER.format(
        ssid=_escape_c_string(ssid),
        password=_escape_c_string(password),
    )
    out_path.write_text(content, encoding="utf-8")
    return out_path


def inject_for_firmware(
    firmware_root: Path,
    firmware_name: str,
    wifi_ssid: str | None = None,
    wifi_password: str | None = None,
) -> tuple[Path, str]:
    firmware_dir = firmware_root / firmware_name
    if not firmware_dir.is_dir():
        raise ValueError(f"Firmware project not found: {firmware_name}")
    creds = resolve_credentials(firmware_root, wifi_ssid, wifi_password)
    path = write_local_header(firmware_dir, creds["ssid"], creds["password"])
    return path, creds["ssid"]
